Move go.mod replaced forks to publicly accessible package.
It's difficult to reference packages externally because of the replace
directive referencing an internal package:

```
$ go install github.com/jonjohnsonjr/dagdotdev/cmd/oci
/Users/wlynch/go/pkg/mod/github.com/jonjohnsonjr/dagdotdev@v0.0.7-0.20240821193425-772575746fe1/internal/soci/indexer.go:25:22: undefined: zstd.Checkpoint
/Users/wlynch/go/pkg/mod/github.com/jonjohnsonjr/dagdotdev@v0.0.7-0.20240821193425-772575746fe1/internal/soci/indexer.go:95:32: undefined: zstd.Checkpoint
/Users/wlynch/go/pkg/mod/github.com/jonjohnsonjr/dagdotdev@v0.0.7-0.20240821193425-772575746fe1/internal/soci/indexer.go:96:38: undefined: zstd.WithCheckpoints
/Users/wlynch/go/pkg/mod/github.com/jonjohnsonjr/dagdotdev@v0.0.7-0.20240821193425-772575746fe1/internal/soci/indexer.go:100:10: cannot use zr (variable of type *"github.com/klauspost/compress/zstd".Decoder) as checkpointReader value in assignment: *"github.com/klauspost/compress/zstd".Decoder does not implement checkpointReader (missing method CompressedCount)
```

This moves the replaced packages from internal -> pkg so that downstream
modules and replicate the same replace behavior.